all: p1 e1 e2 e3 e4 e5 e6 e7 e8

clean:
	rm -f p1 e1 e2 e3 e4 e5 e6 e7 e8

p1: p1.c
	gcc -o p1 p1.c -Wall

e1: e1.c
	gcc -o e1 e1.c -Wall

e2: e2.c
	gcc -o e2 e2.c -Wall

e3: e3.c
	gcc -o e3 e3.c -Wall

e4: e4.c
	gcc -o e4 e4.c -Wall

e5: e5.c
	gcc -o e5 e5.c -Wall

e6: e6.c
	gcc -o e6 e6.c -Wall

e7: e7.c
	gcc -o e7 e7.c -Wall

e8: e8.c
	gcc -o e8 e8.c -Wall